let challenge = "30 Days Of JavaScript"
console.log("2)", challenge)
console.log("3)", challenge.length)
console.log("4)", challenge.toUpperCase())
console.log("5)", challenge.toLowerCase())
console.log("6)", challenge.substring(3)) // substr(0, 1)
console.log("7)", challenge.substring(challenge.length, 4)) // slice(3)
console.log("8)", challenge.includes("Script"))
const challengeArray = challenge.split(" ")
console.log("9)", challengeArray)
console.log("10)", challengeArray)
let companies = "Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon"
const companiesArray = companies.split(", ")
console.log("11)", companiesArray)
console.log("12)", challenge.replace("JavaScript", "Python"))
console.log("13)", challenge.charAt(15)) // charAt("J")
console.log("14)", challenge.charCodeAt(challenge.indexOf("J")))
console.log("15)", challenge.indexOf("a"))
console.log("16)", challenge.lastIndexOf("a"))
let sentence = "You cannot end a sentence with because because because is a conjunction"
console.log("17)", sentence.indexOf("because"))
console.log("18)", sentence.lastIndexOf("because"))
console.log("19)", sentence.search("because"))
console.log("20)", " 30 Days Of JavaScript ".trim())
console.log("21)", challenge.startsWith("30"))
console.log("22)", challenge.endsWith("JavaScript"))
console.log("23)", challenge.match("a"))
console.log("24)", "30 Days of ".concat("JavaScript"))
console.log("25)", challenge.repeat(2))

